name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine version
        id: vars
        run: |
          git fetch --tags
          VERSION=$(git describe --tags --abbrev=0 || echo "0.1.0-$(git rev-parse --short HEAD)")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/httpbin:latest
            ghcr.io/${{ github.repository_owner }}/httpbin:${{ env.VERSION }}

      - name: Post run info
        run: echo "Docker image built and pushed to GitHub Container Registry with tags latest and ${{ env.VERSION }}"
